name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: dart-lang/setup-dart@v1.2
        with:
          sdk: stable
      - name: checkout
        uses: actions/checkout@v2.3.4
      - name: install dependencies
        run: dart pub get
      - name: analyze Dart
        run: dart analyze --fatal-warnings test
      - name: test
        run: dart test

